### ISSUE TITLE
Getting a "TypeError: Cannot read properties of undefined (reading 'err')" with Niagara Obix Vairable

### ISSUE THREAD

**Issue by nadamson87** [adamzman/NodeRed_Niagara_Obix_Node#3] opened 2023-09-13 20:32 UTC
I'm using 4.11 trying to connect to a Station on my workbench.
I have it configured as a batch with the following:
```
[
    {
        "path": "/Points/BooleanWritable",
        "action": "read"
    },
    {
        "path": "/Points/NumericWritable",
        "action": "read"
    }
]
```

I have these points created in the respective ord:
`station:|slot:/Points/BooleanWritable`
and 
`station:|slot:/Points/NumericWritable`

**Comment by adamzman** [comment] 2023-09-14 15:03
I don't seem to be able to reproduce this issue. Is there more information about the error that can be provided? Maybe a call stack can help to see exactly where the issue is coming from.

**Comment by adamzman** [comment] 2023-10-20 16:58
#11 potential fix for this issue

**Closed by adamzman** 2023-10-20 16:58 UTC
